version: '3'

services:
  test-database:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: testdb
      POSTGRES_PASSWORD: testdb
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
